### ISSUE TITLE
Lack of code_of_conduct file in your project

### ISSUE THREAD

**Issue by rishyym0927** [GDSC-RCCIIT/gdg-website#2] opened 2024-10-02 09:07 UTC
Hey can you assign this issue and label it under gssoc-ext level 1

**Comment by rishicds** [comment] 2024-10-11 15:25
@rishyym0927 assigned

**Comment by tarunkumar2005** [comment] 2024-10-16 15:58
I can see the issue is open for 2 weeks and still not fixed so assign this to me i will work on this issue.

**Comment by rishicds** [comment] 2024-10-17 04:56
@tarunkumar2005  assigned

**Closed** 2024-10-18 10:10 UTC
Labels: gssoc-ext, level1
